services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
    cap_add: #This will allow caddy to use their service discovery and configuration to proxy to the backend
      - NET_ADMIN
    depends_on:
      - backend
  backend:
    build: ./backend/
    container_name: backend
    restart: unless-stopped
    #We don't expose ports here because we are using caddy as a reverse proxy