services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
    cap_add:
      - NET_ADMIN
  backend:
    build: ./backend/
    container_name: backend
    depends_on:
      - caddy
    restart: unless-stopped